packages:
  - '.'
  - 'poc'

catalog:
  dotenv: ^16.6.1
  o1js: 2.13.0
  '@types/node': ^20.17.58
  '@typescript/native-preview': 7.0.0-dev.20260218.1
  lefthook: ^2.1.1
  oxfmt: ^0.33.0
  oxlint: ^1.48.0
  tsx: ^4.20.5
  typescript: ^5.8.2
  vitest: ^2.1.8
