# .github/workflows/ci.yml
# Complete moon CI workflow with matrix parallelization and run reports

name: CI Pipeline

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 'CI (${{ matrix.shard }})'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        shard: [0, 1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for affected detection

      - name: Setup Toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Run CI
        run: moon ci --job ${{ matrix.shard }} --job-total 4

      - name: Report Results
        uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          matrix: ${{ toJSON(matrix) }}

---

# Alternative: Split by task type
# .github/workflows/ci-split.yml

name: CI Pipeline (Split)

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: moon ci :build

  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: moon ci :lint :format

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: moon ci :test

---

# Open source multi-platform testing
# .github/workflows/ci-matrix.yml

name: CI Matrix

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  ci:
    name: 'CI (Node ${{ matrix.node }}, ${{ matrix.os }})'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20, 22]

    env:
      MOON_NODE_VERSION: ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - run: moon ci

      - uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          matrix: ${{ toJSON(matrix) }}

---

# CircleCI configuration
# .circleci/config.yml

version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  ci:
    docker:
      - image: cimg/base:stable
    parallelism: 10
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '20'
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
      - run: |
          curl -fsSL https://moonrepo.dev/install/proto.sh | bash
          export PATH="$HOME/.proto/bin:$PATH"
          moon ci --job $CIRCLE_NODE_INDEX --job-total $CIRCLE_NODE_TOTAL

workflows:
  ci:
    jobs:
      - ci

---

# Buildkite configuration
# .buildkite/pipeline.yml

steps:
  - label: 'CI'
    parallelism: 10
    commands:
      - curl -fsSL https://moonrepo.dev/install/proto.sh | bash
      - export PATH="$HOME/.proto/bin:$PATH"
      - proto install
      - moon ci --job $$BUILDKITE_PARALLEL_JOB --job-total $$BUILDKITE_PARALLEL_JOB_COUNT
