$schema: 'https://moonrepo.dev/schemas/workspace.json'

projects:
  workspace: '.'
  poc: 'poc'
  mock-server: 'mock-server'
  tlsnotary: 'tlsnotary'
  ui: 'ui'

pipeline:
  installDependencies: true
